dist: focal
sudo: false
language: python
cache: pip
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37,docs,readme
  - python: 3.7
    env: TOXENV=black
    after_success: skip
  - python: pypy2.7-6.0
    env: TOXENV=pypy
  - python: pypy3.5-6.0
    env: TOXENV=pypy3
before_install:
  - python -m pip install --upgrade pip setuptools
  - python -m pip install tox coveralls
script:
  - tox
after_success:
  - COVERALLS_PARALLEL=true coveralls
notifications:
  webhooks:
    urls:
    - https://coveralls.io/webhook
    on_success: always
    on_failure: always
    on_start: never
